### ISSUE TITLE
Task: Hire research assistant 

### ISSUE THREAD

**Issue by myriamgui** [CUPUM/ai-edi-space#29]
# Task Description
Hire a research assistant to conduct a review as part of the typology of public space article #27.

This literature review consists of the indentification of private, non-profit, and governmental initiatives focusing on the design and the policies regarding public space (grey literature).

# List of actions
- [x] Action: Message student about interest for position
- [ ] Action: Meet with student to discuss task
- [ ] Action: Email Ludovic’s replacement to draft contract
- [ ] Action: Onboard student with task
