### ISSUE TITLE
Epic: Apply to Globalink Research Internship (MEI)

### ISSUE THREAD

**Issue by myriamgui** [CUPUM/ai-edi-space#35]
# Epic Description
Stage de recherche Mitacs Globalink est une initiative concurrentielle pour les finissant·es du premier cycle des régions et pays suivants : Allemagne, Australie, Brésil, Chili, Chine, Colombie, Corée du Sud, États-Unis, France, Hong Kong, Inde, Mexique, Royaume-Uni, Taïwan, Tunisie et Ukraine. De mai à octobre de chaque année, les meilleur·es candidat·es participent à un stage de recherche de 12 semaines sous la supervision de professeur·es d’universités canadiennes de diverses disciplines, des sciences, de l’ingénierie et des mathématiques aux sciences humaines et sociales. 

# List of Tasks (Complete in order)
- [x] Task: Identification du domaine de recherche
- [x] Task: Description du projet
- [x] Identification des compétences requises
- [x] Définition du rôle de l'étudiant
- [x] #36

[Dossier CIRRUS](https://cirrus.gnp.umontreal.ca/index.php/s/tQfrqYdCyy5FAT6)

**Comment by myriamgui** [comment]
@sjinko, @hugobb 

En fait, après analyse du tout, je comprends en lisant la réponse de M. Bousquet de Mitacs qu'une lettre ne peut pas être produite puisque le MEI finance indirectement Mitacs mais que cela ne pose pas d'enjeu car nous n'avons pas à fournir de contrepartie : _Vous pourrez donc assigner votre stagiaire GRI sur un projet financé en tout ou en partie par le MEI sans pour autant engager davantage de dollars de source MEI puisque vous ne rémunérerez pas l’étudiant._ 

Également j'aurais besoin de plus de détails relatifs au stagiaire. Cette personne intervient-elle en tant qu'auxiliaire au niveau du développement de l'algorithme GAN, ce qui semble logique selon notre timeline? Les entretiens seront probablement terminés avant l'été 2023.

**Comment by sjinko** [comment]
Ok, très bien. Oui, je pense que le profile GAN serait utile à l’été 2023, Hugo?

Shin Koseki
Titulaire de la Chaire UNESCO en paysage urbain /
  UNESCO Chair Professor in Urban Landscape
Université de Montréal
________________________________

**Comment by sjinko** [comment]
A. Detolle nous conseille de bien mettre l'accent sur les retombées canadiennes du projet

**Comment by hugobb** [comment]
Oui moi ca me parait bien de pouvoir recruter un stagiaire pour travailler sur les algorithmes à l'été 2023.

**Comment by myriamgui** [comment]
@hugobb, Salut Hugo,

Voila les deux questions dont je te parlais pour le stagiaire MITACS:

_Veuillez décrire les compétences requises et les antécédents que vous recherchez chez l'étudiant_ (100 mots) :

ET

_Veuillez décrire le rôle que devra assumer l'étudiant_ (300 mots maximum) :
La personne étudiante sera amenée à réaliser différentes tâches en lien avec le développement des algorithmes d'intelligence artificielle. Il est question entre autres de …

Ici simplement me donner des bullets points et je vais m'occuper de la rédaction

**Comment by hugobb** [comment]
@myriamgui voici je pense ce qu'il est important d'inclure dans la demande:

> Veuillez décrire les compétences requises et les antécédents que vous recherchez chez l'étudiant (100 mots) :
> - Connaissance de python
> - Connaissance ou expérience précédentes en ML (Machine Learning)
> - Expérience avec une des librairies suivantes: pytorch ou tensorflow
> - Experience avec des modeles generatifs: GANs, VAEs, Diffusion models, etc...
>
> Veuillez décrire le rôle que devra assumer l'étudiant (300 mots maximum) :
> - Implémenter differents modeles generatifs: StyleGAN, GLIDE, etc...
> - Entraîner les différent modèles sur le dataset d'AI EDI Public Space
> - Tester et explorer l'espace latent appris par les différents modèles
> - Conduire une phase de test auprès des participants pour évaluer la qualité des images générer.

**Comment by hugobb** [comment]
Si tu as besoin de plus de détails, tiens moi au courant

**Comment by myriamgui** [comment]
@hugobb C'est parfait, merci!

**Comment by sjinko** [comment]
Salut @myriamgui, le descriptif a l’air très bien. Pourrais-tu créer un task issue pour gérer la soumission à Mitacs et m’assigner si nécessaire. Aussi, je pense qu’étant donné le « pool » de pays visé par le programme, une version en anglais serait nécessaire. Qu’en penses-tu?
