### ISSUE TITLE
Submit to Mitacs Globalink Research Internship by June 8

### ISSUE THREAD

**Issue by myriamgui** [CUPUM/ai-edi-space#36]
# Task Description
Submit to Mitacs Globalink Research Internship following call for faculty applications

CIRRUS [Project folder
](https://cirrus.gnp.umontreal.ca/index.php/s/tQfrqYdCyy5FAT6) created by @myriamgui 

# List of actions
- [x] Submit Mitacs Globalink Research Internship via [Professor Portal](https://globalink.mitacs.ca/#/prof) (Before June 8th) @sjinko 
- [x] Action: @myriamgui --> Transfer application folder to Subventions
- [ ] Action: @sjinko --> Deposit confirmation certificate in folder

**Comment by sjinko** [comment]
@myriamgui @hugobb j‘ai soumis le projet. 
@myriamgui, je ne peux pas éditer le dossier pour y déposer le certificat de confirmation. J’ai ajouté des actions.
