### ISSUE TITLE
Epic: Organiser Journée de recherche (Paysages urbains inclusifs)

### ISSUE THREAD

**Issue by myriamgui** [CUPUM/ai-edi-space#37]
# Epic Description
Organisation d'une journée de recherche au semestre d'automne sur le thème « Paysages urbains inclusifs ».

# List of Tasks (Complete in order)
- [ ] Rédaction d'un appel à communication interne
- [ ] Identification de chercheurs externes 
- [ ] Identification d'intervenants communautaires
- [ ] Planification budgétaire
- [ ] Définition des échéanciers
- [ ] Préparation des communications

**Comment by sjinko** [comment]
@myriamgui  l'appel me semble très bien. J'aimerais si on pouvait lister une série de sujets en exemple comme: 
* l'intersectionalité
* l'espace public
* le numérique
* les expressions culturelles
* la justice spatiale
* etc.

**Comment by SarahTannir** [comment]
Peut-être aussi de clarifier c'est quoi le rendu final (présentation)? 
Tellement intéressant comme événement!

**Comment by myriamgui** [comment]
@sjinko, dans un tel cas, serait-il pertinent d'avoir une adresse courriel de la Chaire à laquelle nous pourrions recevoir les propositions de communication ?

**Comment by sjinko** [comment]
@myriamgui, je préfère éviter qu‘on aille une adresse courriel organisationnelle. Cela occasionne en général plus de problèmes qu’autre chose.
